# Generated by Django 2.1.2 on 2018-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.BooleanField(default=False),
        ),
    ]
