# Generated by Django 2.1.2 on 2018-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=3),
        ),
    ]
