# Generated by Django 2.1.2 on 2018-12-06 11:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181206_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/default/default.png', null=True, upload_to=accounts.models.upload_image_dir),
        ),
    ]
