# Generated by Django 2.1.2 on 2018-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181206_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=3, verbose_name='langage'),
        ),
    ]
