# Generated by Django 2.1.2 on 2018-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181207_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=6, verbose_name='langage'),
        ),
    ]
